
server:
  port: 8761

eureka:
  instance:
    hostname: 118.126.110.234
  client:
    register-with-eureka: false #表示是否将自己注册到eureka server
    fetch-registry: false #是否从eureka server 获取注册信息 单节点为false
    service-url:
      #设置与eureka server 交互地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

ribbon:
  eager-load:
    clients: service-helloworld #饥饿加载模式，将在启动时加载对应的子应用程序上下文，提高首次请求访问速度



